### ISSUE TITLE
Hello, Why is the performance of the latest methods on cifar10 not as good as that of 2015? Would you please take a look at this?

### ISSUE THREAD

**Issue by Xiao-Bai0** [swuxyj/DeepHash-pytorch#11]
Hello, Why is the performance of the latest methods on cifar10 not as good as that of 2015? Would you please take a look at this? Is it due to different evaluation criteria? He got a map value of 93 at cifar10

https://github.com/flyingpot/pytorch_deephash
He's up to 93% of the map

**Comment by swuxyj** [comment]
Different papers may use different dataset configurations 

In the code here, three different configurations for cifar10，You can modify the dataset configuration in the code

Greedyhash used cifar10-2, also  93% map 

config["dataset"]="cifar10" will use 1000 images (100 images per class) as the query set, 5000 images( 500 images per class) as training set , the remaining 54,000 images are used as database.
config["dataset"]="cifar10-1" will use 1000 images (100 images per class) as the query set, the remaining 59,000 images are used as database, 5000 images( 500 images per class) are randomly sampled from the database as training set.
config["dataset"]="cifar10-2" will use 10000 images (1000 images per class) as the query set, 50000 images( 5000 images per class) as training set and database.

**Comment by Xiao-Bai0** [comment]
Thank you for your reply, I have a few questions, please help me, I just contacted image retrieval

1. Using cifar10-2, the map of CSQ has increased by 96.2%. Is this due to the training with the whole database? And the other two data segmentation methods only use part of the database for training?

2. in the process of searching a certain image, is it to determine the category of the current picture first, then search in the current category, or search the Iwhole database?

3. Can I search an image on your basis, and then display the top k image? Do you have any suggestions?

**Comment by Xiao-Bai0** [comment]
How to apply it to my own dataset, just modify the dataloader? Does the subscript of the image have no effec？

**Comment by swuxyj** [comment]
> Thank you for your reply, I have a few questions, please help me, I just contacted image retrieval
> 
> 1. Using cifar10-2, the map of CSQ has increased by 96.2%. Is this due to the training with the whole database? And the other two data segmentation methods only use part of the database for training?
> 2. in the process of searching a certain image, is it to determine the category of the current picture first, then search in the current category, or search the Iwhole database?
> 3. Can I search one image , and then display the top k image? Do you have any suggestions?

1. yes
2. whole
3. You can refer to the code [here ](https://github.com/swuxyj/DeepHash-pytorch/blob/fa5df9497bca40e694c3d471e76acee995715325/demo.ipynb)

**Comment by swuxyj** [comment]
> How to apply it to my own dataset, just modify the dataloader? Does the subscript of the image have no effec？

I suggest you refer to [this code](https://github.com/swuxyj/DeepHash-pytorch/blob/master/data/mirflickr/code.py) to partition your dataset to get  train.txt 、test.txt、database.txt
