### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ysj1173886760** [swuxyj/DeepHash-pytorch#12]
In GreedyHash.py line 66, y_pre is not defined.
I have looked your history commit and think we should add y_pre = self.fc(b) before that line.

**Comment by swuxyj** [comment]
Thank you, I accidentally deleted that line of code.

**Comment by ysj1173886760** [comment]
> Thank you, I accidentally deleted that line of code.

You are the one to be appreciated, I have learned a lot from there, and hope to contribute someday
