### ISSUE TITLE
how to load cifar10 dataset or diy my dataset

### ISSUE THREAD

**Issue by Jingjizhen** [swuxyj/DeepHash-pytorch#13]
Hello, cifar10 download timeout. But I have downloaded the compressed package of cifar10, how to add this to the code. In addition, does the code support other databases？

**Comment by swuxyj** [comment]
你好，不同的版本的pytorch加载cifar的方式可能不一样，我的pytorch版本是1.4.0。
也可能是你cifar10数据目录不对，我本地的cifar10是这样的目录，可以参考一下:
```
(py37) xyj@minecraft:/dataset/cifar$ tree
.
├── cifar-10-batches-py
│   ├── batches.meta
│   ├── data_batch_1
│   ├── data_batch_2
│   ├── data_batch_3
│   ├── data_batch_4
│   ├── data_batch_5
│   ├── readme.html
│   └── test_batch
└── cifar-10-python.tar.gz
```

如果你需要使用自己的数据集，可以参考我写的划分数据集的代码，比如：
https://github.com/swuxyj/DeepHash-pytorch/blob/master/data/voc2012/code.py
https://github.com/swuxyj/DeepHash-pytorch/blob/master/data/mirflickr/code.py
