### ISSUE TITLE
细粒度图像问题

### ISSUE THREAD

**Issue by KayeeWong** [swuxyj/DeepHash-pytorch#15]
您好，我现在在使用一个医学影像细粒度数据集进行试验，然而大部分方法的map值都维持在0.13~0.18这个区间内。我对HashNet这个方法同时用清华本身那套代码和本代码进行了实验，map@10结果分别是：0.38和0.13.
一开始我使用的是代码里默认的优化器设置：
"optimizer": {"type": optim.RMSprop, "optim_params": {"lr": 1e-5, "weight_decay": 10 ** -5}, "lr_type": "step"}
发现结果太低之后，尝试了更改学习率和优化器，然而效果都没有很好地提升。请问有什么好的建议吗？

**Comment by swuxyj** [comment]
现在代码默认用的AlexNet,也许可以使用其他更适合细粒度分类的骨干网络

**Comment by KayeeWong** [comment]
感谢回复。我在thuml/HashNet这套中试过不同的骨架网络，目前是ResNet效果最好。在本套代码中我也试过ResNet50，并没有什么提升。想请问下在学习率的设置上有没有建议？

**Comment by swuxyj** [comment]
没有，之前实践的时候我也用了学习率衰减的，但是学习率衰减没有什么提升，所以我把学习率衰减去掉了。

**Comment by Codeczh** [comment]
> 医学影像细粒度数据集

你好，请问 医学影像细粒度数据集 有相关的survey吗，或者论文，我是做细粒度分类的，想往医学应用上靠，可以一起合作发paper
