### ISSUE TITLE
DSH loss

### ISSUE THREAD

**Issue by KinglittleQ** [swuxyj/DeepHash-pytorch#16]
Should we replace `sign()` with `abs()`?

https://github.com/swuxyj/DeepHash-pytorch/blob/4ee144cf20e8d432b3464a0195b340001cd0ed19/DSH.py#L65

**Comment by swuxyj** [comment]
Sorry， I made a mistake.  
As the paper said: ` |·| is the element-wise absolute value operation`, I read the code written by others [DSH_tensorflow](https://github.com/yg33717/DSH_tensorflow/blob/0d94cffda2d329ab54fb18791cc45c673421a21b/demo.py#L151)、[DSH-pytorch](https://github.com/weixu000/DSH-pytorch/blob/master/main.py#L20)，They all used the abs function.
I will modify the code immediately, thank you for your issue.
