### ISSUE TITLE
coco数据集

### ISSUE THREAD

**Issue by ZiTian8** [swuxyj/DeepHash-pytorch#2]
您好，非常感谢您分享的代码。关于coco数据，请问有国内下载链接吗？我在您给谷歌网盘中下载时，每次下载到一半都会出错无法继续下载。非常感谢。

**Comment by swuxyj** [comment]
您好，抱歉我没有国内下载的链接，也许可以咨询一下HashNet的作者，https://github.com/thuml/HashNet/tree/master/pytorch，我也是从他给的链接下载的coco，但是coco在这里的代码跑起来效果不太理想。

**Comment by ZiTian8** [comment]
好的，非常感谢
