### ISSUE TITLE
IDHN.py和ISDH.py里面的loss名字不对

### ISSUE THREAD

**Issue by Intsigstephon** [swuxyj/DeepHash-pytorch#25]

**Comment by Intsigstephon** [comment]
这这篇虽然名字不一样，但我看只是作者的不同投稿，其内容是一致的；这个loss有复现吗？

**Comment by swuxyj** [comment]
> 这两篇虽然名字不一样，但我看只是作者的不同投稿，其内容是一致的；这个loss有复现吗？

如果现在没有复现的话，那最近也不会复现了，欢迎pull requests新的复现代码![40B51B0IS${ZX AE B(EHRY](https://user-images.githubusercontent.com/35865054/149779202-7b583e56-ded2-40f7-ab6e-13a12ab79b26.png)![40B51B0IS${ZX AE B(EHRY](https://user-images.githubusercontent.com/35865054/149779202-7b583e56-ded2-40f7-ab6e-13a12ab79b26.png)![40B51B0IS${ZX AE B(EHRY](https://user-images.githubusercontent.com/35865054/149779202-7b583e56-ded2-40f7-ab6e-13a12ab79b26.png)
