### ISSUE TITLE
tools.py cifar_dataset_root 路径问题

### ISSUE THREAD

**Issue by liwj72** [swuxyj/DeepHash-pytorch#26]
执行的时候提示无权创建目录，跟踪发现路径错误，建议做以下调整。
原代码：
cifar_dataset_root = '/dataset/cifar/'
建议改成：
cifar_dataset_root = os.getcwd()+'/dataset/cifar/'

**Comment by swuxyj** [comment]
我的服务器上数据放到 '/dataset/cifar/'目录下的，不同人的数据目录可能不一样，你跑代码的时候根据你自己实际目录调整就行
