### ISSUE TITLE
Would anyone be willing to share their pretrained model?

### ISSUE THREAD

**Issue by exnx** [swuxyj/DeepHash-pytorch#3]
Hi!  I am looking to do just inference and would love to avoid retraining on something like ImageNet (I don't have enough gpus).  Would anyone be willing to provide a pretrained model on any of the deep hash models?  DHN, DSH, etc, and on ImageNet or NUS-WIDE or similar.

I would really appreciate it!! Thanks.

**Comment by swuxyj** [comment]
this code has been updated, hope i can help you

**Comment by exnx** [comment]
wow thanks so much @swuxyj !!!

**Comment by exnx** [comment]
Hi @swuxyj, I emailed you some more questions, but maybe I could ask here too.

I'm a researcher at Adobe, and formerly at Facebook AI, working on image hashing.

I was wondering if you're able to share any other pretrained models?  I'm trying to get a few different hash pretrained models for comparison.  You wouldn't have to share any Jupyter notebook (that's more work for you), but sharing the model.pt file only would be fine too!

I was trying to get a pretrained model for HashNet (ImageNet), but the other DSH and DPSH would be super useful too!

And in general, do you have higher hash bit encodings?  64 or 128 for example?  I was trying to do higher resolution images.  No worries if not, I would take any you have easily available.

Sorry to ask for so much, but this would be soooo helpful!  If there's anything I can be helpful with for you as well, please let me know.  Thanks!

Eric
