### ISSUE TITLE
关于cifar10数据集问题

### ISSUE THREAD

**Issue by Zning98** [swuxyj/DeepHash-pytorch#44]
您好，我想问下，我加载了cifar10数据集，怎么找不到train、test和database.txt文件。
还想问下，我是否可以自己加载cifar10，自己生成cifar10的train、test和database.txt来运行，
还有一个疑问，为何这里cifar10数据集要单独处理？谢谢！

**Comment by swuxyj** [comment]
> 您好，我想问下，我加载了cifar10数据集，怎么找不到train、test和database.txt文件。 还想问下，我是否可以自己加载cifar10，自己生成cifar10的train、test和database.txt来运行， 还有一个疑问，为何这里cifar10数据集要单独处理？谢谢！

torchvision.datasets里面有CIFAR10，所以就不需要拿图片数据来加载数据集了。自己也可以手动处理，比如把这些数据转png存到本地，网上应该也有类似的代码。

**Comment by Zning98** [comment]
> > 您好，我想问下，我加载了cifar10数据集，怎么找不到train、test和database.txt文件。 还想问下，我是否可以自己加载cifar10，自己生成cifar10的train、test和database.txt来运行， 还有一个疑问，为何这里cifar10数据集要单独处理？谢谢！
> 
> torchvision.datasets里面有CIFAR10，所以就不需要拿图片数据来加载数据集了。自己也可以手动处理，比如把这些数据转png存到本地，网上应该也有类似的代码。

谢谢你的回答，我已经参考你的代码（code.py）手动加载了本地下载的cifar10图片集，你的代码对我由很大的帮助，再次感谢你的分享！谢谢！

**Comment by CCORAL31** [comment]
> > > 您好，我想问下，我加载了cifar10数据集，怎么找不到train、test和database.txt文件。 还想问下，我是否可以自己加载cifar10，自己生成cifar10的train、test和database.txt来运行， 还有一个疑问，为何这里cifar10数据集要单独处理？谢谢！
> > 
> > 
> > torchvision.datasets里面有CIFAR10，所以就不需要拿图片数据来加载数据集了。自己也可以手动处理，比如把这些数据转png存到本地，网上应该也有类似的代码。
> 
> 谢谢你的回答，我已经参考你的代码（code.py）手动加载了本地下载的cifar10图片集，你的代码对我由很大的帮助，再次感谢你的分享！谢谢！

你好  请问可以分享一下你是如何手动加载了本地下载的cifar10图片集吗?
