### ISSUE TITLE
超参数的问题

### ISSUE THREAD

**Issue by kamwoh** [swuxyj/DeepHash-pytorch#6]
您好，不知道您是否可以分享一下 imagenet 训练超参数 （如果可以的话，所有数据集能不能都分享呢？），
这三个方法在 imagenet 上我都得不到原始文章的分数，都围绕在 0.3~0.5，和原始文章也差太多，用原始文章的超参数也训不了
非常感谢

**Comment by swuxyj** [comment]
由于时间关系，我所有数据集基本上都用的同样的超参数😅，其他文章在ImageNet上复现不出来我也不确定是什么问题(可能他们用的ImageNet数据集用的不是我找的这个？)毕竟我也不是论文作者🥺，不过CSQ在ImageNet上效果是很好的😁。

**Comment by LIWEIJIED** [comment]
请问下CSQ在NUS_WIDE数据集上的超参数吗，我用作者的源代码在64bit的情况下训练的结果只有0.74左右？非常谢谢你

**Comment by swuxyj** [comment]
> 请问下CSQ在NUS_WIDE数据集上的超参数吗，我用作者的源代码在64bit的情况下训练的结果只有0.74左右？非常谢谢你

你好，我之前跑出来的结果是这样的，骨干网络是AlexNet
# [CSQ] epoch:40, bit:16, dataset:nuswide_21, MAP:0.784, Best MAP: 0.789
# [CSQ] epoch:40, bit:32, dataset:nuswide_21, MAP:0.821, Best MAP: 0.821
# [CSQ] epoch:40, bit:64, dataset:nuswide_21, MAP:0.834, Best MAP: 0.834

**Comment by LIWEIJIED** [comment]
> 您好，不知道您是否可以分享一下 imagenet 训练超参数 （如果可以的话，所有数据集能不能都分享呢？），
> 这三个方法在 imagenet 上我都得不到原始文章的分数，都围绕在 0.3~0.5，和原始文章也差太多，用原始文章的超参数也训不了
> 非常感谢

你好，请问您知道CSQ论文中nus_wide上的超参数吗，我只能训练到0.7左右的精确度，一直找不出原因
