### ISSUE TITLE
实验结果

### ISSUE THREAD

**Issue by HHEjie123** [swuxyj/DeepHash-pytorch#8]
请问这些都是您自己复现的吗，我觉得真的很厉害，就想问一下您在代码中所使用的都是论文中的所使用的参数吗，然后map是您自己通过实验所获得的吗

**Comment by swuxyj** [comment]
谢谢你。  
大多数算法都是参考作者或者其他人开源的代码来汇总的，在代码前面的注释中都有写参考来源的，有的没找到开源的代码就只能参考论文来复现，因为很多算法都只是改了下损失函数所以就没有很难。  
不过可能因为很多细节上的问题，好多算法都没法达到论文给的MAP，表格中的MAP是我自己机器上跑出来最优的结果。
参数基本都不是参考论文的，比如很多算法SGD跑起来比较慢，就大都用的RMSprop。
